#!/bin/bash

set -e

if [ -e .env ]
then
  for i in $(cat .env); do export $i; done
fi

PGPASSWORD=$DB_PASSWORD bundle exec sequel -m database/migrations/ postgres://$DB_USER@$DB_HOST:$DB_PORT/$DB_NAME -t $@
